name: Issue Reminder

permissions:
  issues: write  # Allow commenting on issues
  contents: read  # Allow reading repository contents

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get list of open issues
        id: get_issues
        run: |
          issues=$(gh issue list --state open --json number,updatedAt,author --limit 100)
          echo "issues=$issues" >> $GITHUB_ENV

      - name: Send reminders for stale issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REMINDER_DAYS=7
          current_date=$(date +%s)
          for issue in $(echo "$issues" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${issue} | base64 --decode | jq -r ${1}
            }
            issue_number=$(_jq '.number')
            issue_updated_at=$(_jq '.updatedAt')
            issue_author=$(_jq '.author.login')

            updated_at_timestamp=$(date -d $issue_updated_at +%s)
            diff_days=$(( (current_date - updated_at_timestamp) / 86400 ))

            if [ "$diff_days" -ge "$REMINDER_DAYS" ]; then
              echo "Sending reminder to issue #$issue_number"
              gh issue comment "$issue_number" --body "Hi @${issue_author}, this is a friendly reminder that your issue has been inactive for the last $REMINDER_DAYS days. Please provide an update if possible. Thank you!" --repo $GITHUB_REPOSITORY
            fi
          done
