name: 'open-issue reminder'

on:
  schedule:
    - cron: '15 4 * * *'  # This runs daily at 4:15 AM UTC

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment on open issues
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}  # Ensure your PAT has the correct scopes
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            for (const issue of issues) {
              const assignees = issue.assignees.map(assignee => '@' + assignee.login).join(', ') || 'None';
              const issueComment = `Hi there! This issue is still open. We are looking forward to your response.\nAssignees: ${assignees}`;
              
              await github.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: issueComment
              });
            }
