name: Issue Reminder

permissions:
  issues: write  # Required for posting comments on issues
  contents: read  # Required for reading repository contents

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger as well

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/cli@v2.0.0
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}  # Use your custom token here

      - name: Authenticate GitHub CLI with ACTION_TOKEN
        run: gh auth login --with-token <<< ${{ secrets.ACTION_TOKEN }}  # Authenticate with ACTION_TOKEN

      - name: Get list of open issues
        id: get_issues
        run: |
          issues=$(gh issue list --state open --json number,updatedAt,author --limit 100)
          echo "issues=$issues" >> $GITHUB_ENV

      - name: Send reminders for stale issues
        run: |
          # Set the reminder interval in days
          REMINDER_DAYS=7

          # Get the current date (in Unix timestamp format)
          current_date=$(date +%s)

          # Loop through the issues and send reminders for stale ones
          for issue in $(echo "$issues" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${issue} | base64 --decode | jq -r ${1}
            }

            issue_number=$(_jq '.number')
            issue_updated_at=$(_jq '.updatedAt')
            issue_author=$(_jq '.author.login')

            # Convert issue updated date to Unix timestamp
            updated_at_timestamp=$(date -d $issue_updated_at +%s)

            # Calculate the difference in days
            diff_days=$(( (current_date - updated_at_timestamp) / 86400 ))

            # If the issue hasn't been updated in the last $REMINDER_DAYS, send a reminder
            if [ "$diff_days" -ge "$REMINDER_DAYS" ]; then
              echo "Sending reminder to issue #$issue_number"
              gh issue comment "$issue_number" --body "Hi @${issue_author}, this is a friendly reminder that your issue has been inactive for the last $REMINDER_DAYS days. Please provide an update if possible. Thank you!"
            fi
          done
